# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# create_fishnet_full_extent.py
# Created on: 2019-11-06 09:35:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
fishnet_full_extent = "C:\\Users\\Research\\Documents\\ArcGIS\\Default.gdb\\fishnet_full_extent"
fishnet_full_extent_label = "C:\\Users\\Research\\Documents\\ArcGIS\\Default.gdb\\fishnet_full_extent_label"

# Process: Create Fishnet
arcpy.CreateFishnet_management(fishnet_full_extent, "-196806.00234849 76608.5339521042", "-196806.00234849 76618.5339521042", "15", "15", "", "", "692910.061111474 429306.526331396", "NO_LABELS", "Exp_slope_polygon_1000", "POLYGON")

