# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# dosso_index_slope.py
# Created on: 2020-02-05 14:16:41.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

#path for finding files
# path = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index"
# #base string for output files
# outfile = path + "\\fish_125_net_"
# #base string for input files
# infile = path + "\\index"

# clip_in1 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\dosso_slope_1000_la1.tif"
# clip_in2 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\index"
# clip_out = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope_clip"

# poly_in = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope_clip"
# poly_out = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"

# join_in1 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_HWSD_join"
# join_in2 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"
# join_out = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_HWSD_slope"

join_in1 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG60_join"
join_in2 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"
join_out = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG60_slope"

#iterate over all the features
# for i in range(1,347):
#     clip_out_index = clip_out + str(i)
#     clip_in2_index = clip_in2 + str(i) + ".shp"
#     for row in arcpy.da.SearchCursor(clip_in2_index, ['SHAPE@', 'FID']):
#         extent = row[0].extent
#         left = extent.XMin
#         bottom = extent.YMin
#         right = extent.XMax
#         top = extent.YMax
#
#     # Process: Clip
#     arcpy.Clip_management(clip_in1, str(left) + " " + str(bottom) + " " + str(right) +" "+ str(top),
#                           clip_out_index, clip_in2_index, "-2147483647", "ClippingGeometry", "MAINTAIN_EXTENT")




# for i in range(1,347):
#     poly_in_index = clip_out + str(i)
#     poly_out_index = poly_out + str(i) + ".shp"
#     # Process: Raster to Polygon
#     arcpy.RasterToPolygon_conversion(poly_in_index, poly_out_index, "SIMPLIFY", "VALUE", "SINGLE_OUTER_PART", "")

for i in range(1):
    join_in1_index = join_in1 + str(i) + ".shp"
    join_in2_index = join_in2 + str(i) + ".shp"
    join_out_index = join_out + str(i) + ".shp"

    # Process: Spatial Join
    # arcpy.SpatialJoin_analysis(join_in1_index, join_in2_index, join_out_index, "JOIN_ONE_TO_ONE",
    #                            "KEEP_ALL",
    #                            "Join_Count \"Join_Count\" true true false 10 Long 0 10 ,First,#," + join_in1_index + ",Join_Count,-1,-1;TARGET_FID \"TARGET_FID\" true true false 10 Long 0 10 ,First,#," + join_in1_index + ",TARGET_FID,-1,-1;OBJECTID \"OBJECTID\" true true false 10 Long 0 10 ,First,#," + join_in1_index + ",OBJECTID,-1,-1;ID \"ID\" true true false 0 Long 0 0 ,First,#," + join_in2_index + ",ID,-1,-1;GRIDCODE \"GRIDCODE\" true true false 0 Long 0 0 ,First,#," + join_in2_index + ",gridcode,-1,-1",
    #                            "INTERSECT", "", "")
    arcpy.SpatialJoin_analysis(join_in1_index, join_in2_index, join_out_index, "JOIN_ONE_TO_ONE", "KEEP_ALL", "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#," + join_in1_index + ",bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#," + join_in1_index + ",cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#," + join_in1_index + ",clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#," + join_in1_index + ",course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#," + join_in1_index + ",silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#," + join_in1_index + ",sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#," + join_in1_index + ",ph,-1,-1;org_c_cont \"org_c_cont\" true true false 13 Float 0 0 ,First,#," + join_in1_index + ",org_c_cont,-1,-1;prob_class \"prob_class\" true true false 13 Float 0 0 ,First,#," + join_in1_index + ",prob_class,-1,-1;gridcode \"gridcode\" true true false 10 Long 0 10 ,First,#," + join_in2_index + ",gridcode,-1,-1", "INTERSECT", "", "")


