# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# dosso_index_hwsd_merge.py
# Created on: 2020-02-05 11:04:07.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
base_HWSD_join0 = "base_HWSD_join0"
base_HWSD_join0__2_ = base_HWSD_join0
HWSd_dosso_la = "HWSd_dosso_la"

# Process: Add Join
arcpy.AddJoin_management(base_HWSD_join0, "OBJECTID", HWSd_dosso_la, "OBJECTID", "KEEP_ALL")

