# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# dosso_index_base.py
# Created on: 2020-01-31 10:34:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
infile1 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\fish_125_net_"
infile2 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\index"
outfile = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base"
for i in range(347):
    outfile_index = outfile + str(i) + ".shp"
    infile1_index = infile1 + str(i) + ".shp"
    infile2_index = infile2 + str(i) + ".shp"
# Process: Clip
    arcpy.Clip_analysis(infile1_index, infile2_index, outfile_index, "")

