# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# dosso_fish.py
# Created on: 2020-01-08 10:10:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
dosso_region_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso_region_fish.shp"
dosso_region_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso_region_fish_label.shp"
dosso_region_erase = "C:\Users\Research\Documents\ArcGIS\Default.gdb\dosso_region_Erase.shp"
# Process: Create Fishnet
arcpy.CreateFishnet_management(dosso_region_fish_shp, "-56874.4652709961 77001.0059204102", "-56874.4652709961 77011.0059204102", "12.5", "12.5", "", "", "175430.166015625 405070.938903807", "NO_LABELS", dosso_region_erase, "POLYGON")

