# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# dosso_index_soil_join.py
# Created on: 2020-02-03 09:10:45.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Local variables:
# infile1 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base"
# infile2 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\HWSd_dosso_la.shp"
# outfile = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_HWSD_join"
#

infile1 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base"
infile2 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_0cm_dosso.shp"
outfile = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG0_join"
#
# infile1_5 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base"
# infile2_5 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_5cm_dosso.shp"
# outfile_5 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG5_join"
#
# infile1_15 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base"
# infile2_15 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_15cm_dosso.shp"
# outfile_15 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG15_join"
#
# infile1_30 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base"
# infile2_30 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_30m_dosso.shp"
# outfile_30 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG30_join"
#
# infile1_60 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base"
# infile2_60 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_60cm_dosso.shp"
# outfile_60 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG60_join"
#
# infile1_100 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base"
# infile2_100 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_100cm_dosso.shp"
# outfile_100 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG100_join"

#SoilGrids merging
# for i in range(1):
# for i in [0,69,116]:
#     outfile_index = outfile + str(i) + ".shp"
#     infile1_index = infile1 + str(i) + ".shp"
#
# # Process: spatial Join
#     arcpy.SpatialJoin_analysis(infile1_index, infile2, outfile_index, "JOIN_ONE_TO_ONE", "KEEP_ALL",
#                                "OBJECTID \"OBJECTID\" true true false 10 Long 0 10 ,First,#,infile2,OBJECTID,-1,-1",
#                                "INTERSECT", "", "")

for i in range(347):
    outfile_index = outfile + str(i) + ".shp"
    infile1_index = infile1 + str(i) + ".shp"

# Process: spatial Join
    arcpy.SpatialJoin_analysis(infile1_index, infile2, outfile_index, "JOIN_ONE_TO_ONE", "KEEP_ALL",
                               "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_0cm_dosso.shp,bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_0cm_dosso.shp,cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_0cm_dosso.shp,clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_0cm_dosso.shp,course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_0cm_dosso.shp,silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_0cm_dosso.shp,sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_0cm_dosso.shp,ph,-1,-1;org_c_cont \"org_c_cont\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_0cm_dosso.shp,org_c_cont,-1,-1",
                               "INTERSECT", "", "")
#
#     outfile_index5 = outfile_5 + str(i) + ".shp"
#     infile1_index5 = infile1_5 + str(i) + ".shp"
#
#     # Process: spatial Join
#     arcpy.SpatialJoin_analysis(infile1_index5, infile2_5, outfile_index5, "JOIN_ONE_TO_ONE", "KEEP_ALL",
#                                "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_5cm_dosso.shp,bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_5cm_dosso.shp,cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_5cm_dosso.shp,clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_5cm_dosso.shp,course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_5cm_dosso.shp,silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_5cm_dosso.shp,sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_5cm_dosso.shp,ph,-1,-1;org_c_cont \"org_c_cont\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_5cm_dosso.shp,org_c_cont,-1,-1",
#                                "INTERSECT", "", "")
#
#     outfile_index15 = outfile_15 + str(i) + ".shp"
#     infile1_index15 = infile1_15 + str(i) + ".shp"
#
#     # Process: spatial Join
#     arcpy.SpatialJoin_analysis(infile1_index15, infile2_15, outfile_index15, "JOIN_ONE_TO_ONE", "KEEP_ALL",
#                                "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_15cm_dosso.shp,bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_15cm_dosso.shp,cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_15cm_dosso.shp,clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_15cm_dosso.shp,course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_15cm_dosso.shp,silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_15cm_dosso.shp,sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_15cm_dosso.shp,ph,-1,-1;org_c_cont \"org_c_cont\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_15cm_dosso.shp,org_c_cont,-1,-1",
#                                "INTERSECT", "", "")
#
#     outfile_index30 = outfile_30 + str(i) + ".shp"
#     infile1_index30 = infile1_30 + str(i) + ".shp"
#
#     # Process: spatial Join
#     arcpy.SpatialJoin_analysis(infile1_index30, infile2_30, outfile_index30, "JOIN_ONE_TO_ONE", "KEEP_ALL",
#                                "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_30m_dosso.shp,bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_30m_dosso.shp,cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_30m_dosso.shp,clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_30m_dosso.shp,course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_30m_dosso.shp,silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_30m_dosso.shp,sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_30m_dosso.shp,ph,-1,-1;org_c_cont \"org_c\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_30m_dosso.shp,org_c_cont,-1,-1",
#                                "INTERSECT", "", "")
#
#     outfile_index60 = outfile_60 + str(i) + ".shp"
#     infile1_index60 = infile1_60 + str(i) + ".shp"
#
#     # Process: spatial Join
#     arcpy.SpatialJoin_analysis(infile1_index60, infile2_60, outfile_index60, "JOIN_ONE_TO_ONE", "KEEP_ALL",
#                                "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_60cm_dosso.shp,bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_60cm_dosso.shp,cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_60cm_dosso.shp,clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_60cm_dosso.shp,course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_60cm_dosso.shp,silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_60cm_dosso.shp,sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_60cm_dosso.shp,ph,-1,-1;org_c_cont \"org_c_cont\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_60cm_dosso.shp,org_c_cont,-1,-1",
#                                "INTERSECT", "", "")
#
#     outfile_index100 = outfile_100 + str(i) + ".shp"
#     infile1_index100 = infile1_100 + str(i) + ".shp"
#
#     # Process: spatial Join
#     arcpy.SpatialJoin_analysis(infile1_index100, infile2_100, outfile_index100, "JOIN_ONE_TO_ONE", "KEEP_ALL",
#                                "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_100cm_dosso.shp,bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_100cm_dosso.shp,cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_100cm_dosso.shp,clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_100cm_dosso.shp,course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_100cm_dosso.shp,silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_100cm_dosso.shp,sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_100cm_dosso.shp,ph,-1,-1;org_c_cont \"org_c\" true true false 13 Float 0 0 ,First,#,C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\SoilGrid_100cm_dosso.shp,org_c_cont,-1,-1",
#                                "INTERSECT", "", "")

    # HWSD merging

# slope_in10 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_HWSD_join"
# slope_in20 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"
# slope_out0 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_HWSD_slope"

slope_in10 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG0_join"
slope_in20 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"
slope_out0 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG0_slope"

# slope_in15 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG5_join"
# slope_in25 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"
# slope_out5 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG5_slope"
#
# slope_in115 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG15_join"
# slope_in215 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"
# slope_out15 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG15_slope"
#
# slope_in130 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG30_join"
# slope_in230 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"
# slope_out30 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG30_slope"
#
# slope_in160 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG60_join"
# slope_in260 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"
# slope_out60 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG60_slope"
#
# slope_in1100 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG100_join"
# slope_in2100 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\slope"
# slope_out100 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\base_SG100_slope"
# for i in [0,69,116]:
    # slope_in1_index0 = slope_in10 + str(i) + ".shp"
    # slope_in2_index0 = slope_in20 + str(i) + ".shp"
    # slope_out_index0 = slope_out0 + str(i) + ".shp"
    #
    # # Process: Spatial Join
    # arcpy.SpatialJoin_analysis(slope_in1_index0, slope_in2_index0, slope_out_index0, "JOIN_ONE_TO_ONE", "KEEP_ALL", "OBJECTID \"OBJECTID\" true true false 13 Float 0 0 ,First,#," + slope_in1_index0 + ",OBJECTID,-1,-1;gridcode \"gridcode\" true true false 10 Long 0 10 ,First,#," + slope_in2_index0 + ",gridcode,-1,-1", "INTERSECT", "", "")


for i in range(347):
    slope_in1_index0 = slope_in10 + str(i) + ".shp"
    slope_in2_index0 = slope_in20 + str(i) + ".shp"
    slope_out_index0 = slope_out0 + str(i) + ".shp"

    # Process: Spatial Join
    arcpy.SpatialJoin_analysis(slope_in1_index0, slope_in2_index0, slope_out_index0, "JOIN_ONE_TO_ONE", "KEEP_ALL", "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#," + slope_in1_index0 + ",bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#," + slope_in1_index0 + ",cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#," + slope_in1_index0 + ",clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#," + slope_in1_index0 + ",course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#," + slope_in1_index0 + ",silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#," + slope_in1_index0 + ",sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#," + slope_in1_index0 + ",ph,-1,-1;org_c_cont \"org_c_cont\" true true false 13 Float 0 0 ,First,#," + slope_in1_index0 + ",org_c_cont,-1,-1;gridcode \"gridcode\" true true false 10 Long 0 10 ,First,#," + slope_in2_index0 + ",gridcode,-1,-1", "INTERSECT", "", "")

    # slope_in1_index5 = slope_in15 + str(i) + ".shp"
    # slope_in2_index5 = slope_in25 + str(i) + ".shp"
    # slope_out_index5 = slope_out5 + str(i) + ".shp"
    #
    # # Process: Spatial Join
    # arcpy.SpatialJoin_analysis(slope_in1_index5, slope_in2_index5, slope_out_index5, "JOIN_ONE_TO_ONE", "KEEP_ALL", "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#," + slope_in1_index5 + ",bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#," + slope_in1_index5 + ",cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#," + slope_in1_index5 + ",clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#," + slope_in1_index5 + ",course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#," + slope_in1_index5 + ",silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#," + slope_in1_index5 + ",sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#," + slope_in1_index5 + ",ph,-1,-1;org_c_cont \"org_c_cont\" true true false 13 Float 0 0 ,First,#," + slope_in1_index5 + ",org_c_cont,-1,-1;gridcode \"gridcode\" true true false 10 Long 0 10 ,First,#," + slope_in2_index5+ ",gridcode,-1,-1", "INTERSECT", "", "")
    #
    # slope_in1_index15 = slope_in115 + str(i) + ".shp"
    # slope_in2_index15 = slope_in215 + str(i) + ".shp"
    # slope_out_index15 = slope_out15 + str(i) + ".shp"
    #
    # # Process: Spatial Join
    # arcpy.SpatialJoin_analysis(slope_in1_index15, slope_in2_index15, slope_out_index15, "JOIN_ONE_TO_ONE", "KEEP_ALL", "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#," + slope_in1_index15 + ",bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#," + slope_in1_index15 + ",cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#," + slope_in1_index15 + ",clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#," + slope_in1_index15 + ",course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#," + slope_in1_index15 + ",silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#," + slope_in1_index15 + ",sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#," + slope_in1_index15 + ",ph,-1,-1;org_c_cont \"org_c_cont\" true true false 13 Float 0 0 ,First,#," + slope_in1_index15 + ",org_c_cont,-1,-1;gridcode \"gridcode\" true true false 10 Long 0 10 ,First,#," + slope_in2_index15 + ",gridcode,-1,-1", "INTERSECT", "", "")
    #
    # slope_in1_index30 = slope_in130 + str(i) + ".shp"
    # slope_in2_index30 = slope_in230 + str(i) + ".shp"
    # slope_out_index30 = slope_out30 + str(i) + ".shp"
    #
    # # Process: Spatial Join
    # arcpy.SpatialJoin_analysis(slope_in1_index30, slope_in2_index30, slope_out_index30, "JOIN_ONE_TO_ONE", "KEEP_ALL",
    #                            "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#," + slope_in1_index30 + ",bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#," + slope_in1_index30 + ",cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#," + slope_in1_index30 + ",clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#," + slope_in1_index30 + ",course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#," + slope_in1_index30 + ",silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#," + slope_in1_index30 + ",sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#," + slope_in1_index30 + ",ph,-1,-1;org_c_cont \"org_c\" true true false 13 Float 0 0 ,First,#," + slope_in1_index30 + ",org_c_cont,-1,-1;gridcode \"gridcode\" true true false 10 Long 0 10 ,First,#," + slope_in2_index30 + ",gridcode,-1,-1", "INTERSECT", "", "")
    #
    #
    # slope_in1_index100 = slope_in1100 + str(i) + ".shp"
    # slope_in2_index100 = slope_in2100 + str(i) + ".shp"
    # slope_out_index100 = slope_out100 + str(i) + ".shp"
    #
    # # Process: Spatial Join
    # arcpy.SpatialJoin_analysis(slope_in1_index100, slope_in2_index100, slope_out_index100, "JOIN_ONE_TO_ONE", "KEEP_ALL", "bulk_dens \"bulk_dens\" true true false 13 Float 0 0 ,First,#," + slope_in1_index100 + ",bulk_dens,-1,-1;cec \"cec\" true true false 13 Float 0 0 ,First,#," + slope_in1_index100 + ",cec,-1,-1;clay \"clay\" true true false 13 Float 0 0 ,First,#," + slope_in1_index100 + ",clay,-1,-1;course_fra \"course_fra\" true true false 13 Float 0 0 ,First,#," + slope_in1_index100 + ",course_fra,-1,-1;silt \"silt\" true true false 13 Float 0 0 ,First,#," + slope_in1_index100 + ",silt,-1,-1;sand \"sand\" true true false 13 Float 0 0 ,First,#," + slope_in1_index100 + ",sand,-1,-1;ph \"ph\" true true false 13 Float 0 0 ,First,#," + slope_in1_index100 + ",ph,-1,-1;org_c_cont \"org_c\" true true false 13 Float 0 0 ,First,#," + slope_in1_index100 + ",org_c_cont,-1,-1;gridcode \"gridcode\" true true false 10 Long 0 10 ,First,#," + slope_in2_index100 + ",gridcode,-1,-1", "INTERSECT", "", "")

