# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# dosso_fish_pieces.py
# Created on: 2020-01-08 12:43:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
# dosso1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso1_fish.shp"
# dosso1_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso1_fish_label.shp"
# dosso2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso2_fish.shp"
# dosso2_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso2_fish_label.shp"
# doso3_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\doso3_fish.shp"
# doso3_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\doso3_fish_label.shp"
dosso4_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso4_fish.shp"
dosso4_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso4_fish_label.shp"
dosso4_clip = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso4_clip.shp"
# dosso5_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso5_fish.shp"
# dosso5_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso5_fish_label.shp"
# dosso6_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso6_fish.shp"
# dosso6_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso6_fish_label.shp"
# dosso7_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso7_fish.shp"
# dosso7_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso7_fish_label.shp"
# dosso8_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso8_fish.shp"
# dosso8_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso8_fish_label.shp"
# doso9_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\doso9_fish.shp"
# doso9_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\doso9_fish_label.shp"
# dosso10_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso10_fish.shp"
# dosso10_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso10_fish_label.shp"
# dosso11_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso11_fish.shp"
# dosso11_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso11_fish_label.shp"
# dosso12_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso12_fish.shp"
# dosso12_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso12_fish_label.shp"
# dosso14_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso14_fish.shp"
# dosso14_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso14_fish_label.shp"
# dosso15_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso15_fish.shp"
# dosso15_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso15_fish_label.shp"
# dosso16_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso16_fish.shp"
# dosso16_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso16_fish_label.shp"
# dosso17_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso17_fish.shp"
# dosso17_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso17_fish_label.shp"
# dosso18_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso18_fish.shp"
# dosso18_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso18_fish_label.shp"
# dosso19_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso19_fish.shp"
# dosso19_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso19_fish_label.shp"
# dosso20_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso20_fish.shp"
# dosso20_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso20_fish_label.shp"
# dosso21_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso21_fish.shp"
# dosso21_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso21_fish_label.shp"
# dosso22_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso22_fish.shp"
# dosso22_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso22_fish_label.shp"
# dosso23_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso23_fish.shp"
# dosso23_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso23_fish_label.shp"

# Process: Create Fishnet
#arcpy.CreateFishnet_management(dosso1_fish_shp, "112884.1856 377001.005899999", "112884.1856 377011.005899999", "12.5", "12.5", "", "", "143125.5348 405070.938899999", "NO_LABELS", "dosso1_Clip", "POLYGON")

# Process: Create Fishnet (2)
#arcpy.CreateFishnet_management(dosso2_fish_shp, "143125.534729003 377001.005920409", "143125.534729003 377011.005920409", "12.5", "12.5", "", "", "154008.123449091 400321.876608208", "NO_LABELS", "dosso2_clip", "POLYGON")

# Process: Create Fishnet (3)
#arcpy.CreateFishnet_management(doso3_fish_shp, "70957.7684259261 327001.00592041", "70957.7684259261 327011.00592041", "12.5", "12.5", "", "", "93125.5347290028 366652.152594876", "NO_LABELS", "dosso3_clip", "POLYGON")

# Process: Create Fishnet (4)
arcpy.CreateFishnet_management(dosso4_fish_shp, "93125.5347290028 327001.00592041", "93125.5347290028 327011.00592041", "12.5", "12.5", "", "", "143125.534729004 377001.005920411", "NO_LABELS", dosso4_clip, "POLYGON")

# # Process: Create Fishnet (5)
# arcpy.CreateFishnet_management(dosso5_fish_shp, "143125.534729003 327001.00592041", "143125.534729003 327011.00592041", "12.5", "12.5", "", "", "165781.208134709 377001.005920411", "NO_LABELS", "dosso5_clip", "POLYGON")
#
# # Process: Create Fishnet (6)
# arcpy.CreateFishnet_management(dosso6_fish_shp, "-14011.8794555662 277001.005920411", "-14011.8794555662 277011.005920411", "12.5", "12.5", "", "", "-6874.46527099705 280054.711166342", "NO_LABELS", "dosso6_clip", "POLYGON")
#
# # Process: Create Fishnet (7)
# arcpy.CreateFishnet_management(dosso7_fish_shp, "-6874.46527099705 277001.005920411", "-6874.46527099705 277011.005920411", "12.5", "12.5", "", "", "43125.5347290043 310879.083984376", "NO_LABELS", "dosso7_clip", "POLYGON")
#
# # Process: Create Fishnet (8)
# arcpy.CreateFishnet_management(dosso8_fish_shp, "43125.5347290043 277001.005920411", "43125.5347290043 277011.005920411", "12.5", "12.5", "", "", "93125.5347290028 327001.00592041", "NO_LABELS", "dosso8_clip", "POLYGON")
#
# # Process: Create Fishnet (9)
# arcpy.CreateFishnet_management(doso9_fish_shp, "93125.5347290028 277001.005920411", "93125.5347290028 277011.005920411", "12.5", "12.5", "", "", "143125.534729004 327001.00592041", "NO_LABELS", "dosso9_clip", "POLYGON")
#
# # Process: Create Fishnet (10)
# arcpy.CreateFishnet_management(dosso10_fish_shp, "143125.534729003 285683.140528878", "143125.534729003 285693.140528878", "12.5", "12.5", "", "", "175430.166015624 327001.00592041", "NO_LABELS", "dosso10_clip", "POLYGON")
#
# # Process: Create Fishnet (11)
# arcpy.CreateFishnet_management(dosso11_fish_shp, "-56874.4652709956 227001.00592041", "-56874.4652709956 227011.00592041", "12.5", "12.5", "", "", "-6874.46527099705 277001.005920411", "NO_LABELS", "dosso11_clip", "POLYGON")
#
# # Process: Create Fishnet (12)
# arcpy.CreateFishnet_management(dosso12_fish_shp, "-6874.46527099705 227001.00592041", "-6874.46527099705 227011.00592041", "12.5", "12.5", "", "", "43125.5347290043 277001.005920411", "NO_LABELS", "dosso12_clip", "POLYGON")
#
# # Process: Create Fishnet (13)
# arcpy.CreateFishnet_management(dosso14_fish_shp, "93125.5347290028 227001.00592041", "93125.5347290028 227011.00592041", "12.5", "12.5", "", "", "133401.544057246 277001.005920411", "NO_LABELS", "dosso14_clip", "POLYGON")
#
# # Process: Create Fishnet (14)
# arcpy.CreateFishnet_management(dosso15_fish_shp, "-53202.8202130517 196736.317849104", "-53202.8202130517 196746.317849104", "12.5", "12.5", "", "", "-6874.46527099705 227001.00592041", "NO_LABELS", "dosso15_clip", "POLYGON")
#
# # Process: Create Fishnet (15)
# arcpy.CreateFishnet_management(dosso16_fish_shp, "-6874.46527099705 177001.005920412", "-6874.46527099705 177011.005920412", "12.5", "12.5", "", "", "43125.5347290043 227001.00592041", "NO_LABELS", "dosso16_clip", "POLYGON")
#
# # Process: Create Fishnet (16)
# arcpy.CreateFishnet_management(dosso17_fish_shp, "43125.5347290043 177001.005920412", "43125.5347290043 177011.005920412", "12.5", "12.5", "", "", "93125.5347290028 227001.00592041", "NO_LABELS", "dosso17_clip", "POLYGON")
#
# # Process: Create Fishnet (17)
# arcpy.CreateFishnet_management(dosso18_fish_shp, "43125.5347290043 177001.005920412", "43125.5347290043 177011.005920412", "12.5", "12.5", "", "", "93125.5347290028 227001.00592041", "NO_LABELS", "dosso17_clip", "POLYGON")
#
# # Process: Create Fishnet (18)
# arcpy.CreateFishnet_management(dosso19_fish_shp, "-28299.4080810534 145041.358644446", "-28299.4080810534 145051.358644446", "12.5", "12.5", "", "", "-6874.46527099705 161649.785879906", "NO_LABELS", "dosso19_clip", "POLYGON")
#
# # Process: Create Fishnet (19)
# arcpy.CreateFishnet_management(dosso20_fish_shp, "-6874.46527099705 127001.00592041", "-6874.46527099705 127011.00592041", "12.5", "12.5", "", "", "43125.5347290043 177001.005920412", "NO_LABELS", "dosso20_clip", "POLYGON")
#
# # Process: Create Fishnet (20)
# arcpy.CreateFishnet_management(dosso21_fish_shp, "43125.5347290043 127001.00592041", "43125.5347290043 127011.00592041", "12.5", "12.5", "", "", "79922.507646227 177001.005920412", "NO_LABELS", "dosso21_clip", "POLYGON")
#
# # Process: Create Fishnet (21)
# arcpy.CreateFishnet_management(dosso22_fish_shp, "14656.6981072921 97807.63014746", "14656.6981072921 97817.63014746", "12.5", "12.5", "", "", "43125.5347290043 127001.00592041", "NO_LABELS", "dosso22_clip", "POLYGON")
#
# # Process: Create Fishnet (22)
# arcpy.CreateFishnet_management(dosso23_fish_shp, "43125.5347290043 77001.0059204088", "43125.5347290043 77011.0059204088", "12.5", "12.5", "", "", "74611.2262573286 127001.00592041", "NO_LABELS", "dosso23_clip", "POLYGON")

