# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# dosso_fish_morepieces.py
# Created on: 2020-01-08 13:43:47.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
# dosso4_1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso4_1_fish.shp"
# dosso4_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso4_fish_label.shp"
# d41 = "C:\Users\Research\Documents\Tara_Fall_2019\dosso_analysis\dosso4_1_clip.shp"
#
# dosso5_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso5_fish.shp"
# dosso5_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso5_fish_label.shp"
# d5 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso5_clip.shp"
#
# dosso6_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso6_fish.shp"
# dosso6_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso6_fish_label.shp"
# d6 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso6_clip.shp"
#
# dosso7_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso7_fish.shp"
# dosso7_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso7_fish_label.shp"
# d7 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso7_clip.shp"
#
# dosso8_1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso8_1_fish.shp"
# dosso8_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso8_fish_label.shp"
# d81 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso8_1_clip.shp"
#
# dosso9_1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso9_1_fish.shp"
# doso9_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\doso9_fish_label.shp"
# d91 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso9_1.shp"
#
# dosso10_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso10_fish.shp"
# dosso10_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso10_fish_label.shp"
# d10 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso10_clip.shp"
#
# dosso11_1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso11_1_fish.shp"
# dosso11_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso11_fish_label.shp"
# d111 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso11_1_clip.shp"
#
# dosso12_1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso12_1_fish.shp"
# dosso12_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso12_fish_label.shp"
# d121 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso12_1.shp"
#
# dosso14_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso14_fish.shp"
# dosso14_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso14_fish_label.shp"
# d14 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso14_clip.shp"
#
# dosso15_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso15_fish.shp"
# dosso15_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso15_fish_label.shp"
# d15 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso15_clip.shp"
#
# dosso16_1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso16_1_fish.shp"
# dosso16_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso16_fish_label.shp"
# d161 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso16_1_clip.shp"
#
# dosso17_1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso17_1_fish.shp"
# dosso17_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso17_fish_label.shp"
# d171 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso17_1.shp"
#
# dosso18_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso18_fish.shp"
# dosso18_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso18_fish_label.shp"
# d18 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso18_clip.shp"

dosso19_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso19_fish.shp"
dosso19_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso19_fish_label.shp"
d19 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso19_clip.shp"

dosso20_1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso20_1_fish.shp"
d201 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso20_1_clip.shp"

dosso20_2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso20_2_fish.shp"
d202 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso20_2_clip.shp"

dosso21_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso21_fish.shp"
dosso21_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso21_fish_label.shp"
d21 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso21_clip.shp"

dosso22_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso22_fish.shp"
dosso22_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso22_fish_label.shp"
d22 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso22_clip.shp"

dosso23_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso23_fish.shp"
dosso23_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso23_fish_label.shp"
d23 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso23_clip.shp"

dosso4_2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso4_2_fish.shp"
dosso4_fish_label_shp__3_ = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso4_fish_label.shp"
d42 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso4_2_clip.shp"

dosso8_2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso8_2_fish.shp"
dosso8_fish_label_shp__3_ = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso8_fish_label.shp"
d82 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso8_2_clip.shp"

dosso9_2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso9_2_fish.shp"
doso9_fish_label_shp__3_ = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\doso9_fish_label.shp"
d92 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso9_2_clip.shp"

dosso13_1_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso13_1_fish.shp"
dosso13_1_fish_label_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso13_1_fish_label.shp"
d131 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso13_1.shp"

dosso13_2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso13_2_fish.shp"
dosso13_1_fish_label_shp__3_ = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso13_1_fish_label.shp"
d132 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso13_2.shp"

dosso12_2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso12_2_fish.shp"
dosso14_fish_label_shp__3_ = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso14_fish_label.shp"
d122 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso12_2.shp"

dosso16_2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso16_2_fish.shp"
dosso16_fish_label_shp__3_ = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso16_fish_label.shp"
d162 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso16_2_clip.shp"

dosso17_2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso17_2_fish.shp"
dosso17_fish_label_shp__3_ = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso17_fish_label.shp"
d172 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso17_2_clip.shp"

dosso11_2_fish_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso11_2_fish.shp"
dosso11_fish_label_shp__3_ = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso11_fish_label.shp"
d112 = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_analysis\\dosso11_2_clip.shp"


# Process: Create Fishnet (4)
# arcpy.CreateFishnet_management(dosso4_1_fish_shp, "93125.5347290028 327001.00592041", "93125.5347290028 327011.00592041", "12.5", "12.5", "", "", "118125.534729002 377001.005920411", "NO_LABELS", d41, "POLYGON")
#
# # Process: Create Fishnet (5)
# arcpy.CreateFishnet_management(dosso5_fish_shp, "143125.534729003 327001.00592041", "143125.534729003 327011.00592041", "12.5", "12.5", "", "", "165781.208134709 377001.005920411", "NO_LABELS", d5, "POLYGON")
#
# # Process: Create Fishnet (6)
# arcpy.CreateFishnet_management(dosso6_fish_shp, "-14011.8794555662 277001.005920411", "-14011.8794555662 277011.005920411", "12.5", "12.5", "", "", "-6874.46527099705 280054.711166342", "NO_LABELS", d6, "POLYGON")
#
# # Process: Create Fishnet (7)
# arcpy.CreateFishnet_management(dosso7_fish_shp, "-6874.46527099705 277001.005920411", "-6874.46527099705 277011.005920411", "12.5", "12.5", "", "", "43125.5347290043 310879.083984376", "NO_LABELS", d7, "POLYGON")
#
# # Process: Create Fishnet (8)
# arcpy.CreateFishnet_management(dosso8_1_fish_shp, "43125.5347290043 277001.005920411", "43125.5347290043 277011.005920411", "12.5", "12.5", "", "", "68125.5347290036 324476.623732045", "NO_LABELS", d81, "POLYGON")
#
# # Process: Create Fishnet (9)
# arcpy.CreateFishnet_management(dosso9_1_fish_shp, "93125.5347290028 277001.005920411", "93125.5347290028 277011.005920411", "12.5", "12.5", "", "", "118125.534729003 327001.005920411", "NO_LABELS", d91, "POLYGON")
#
# # Process: Create Fishnet (10)
# arcpy.CreateFishnet_management(dosso10_fish_shp, "143125.534729003 285683.140528878", "143125.534729003 285693.140528878", "12.5", "12.5", "", "", "175430.166015624 327001.00592041", "NO_LABELS", d10, "POLYGON")
#
# # Process: Create Fishnet (11)
# arcpy.CreateFishnet_management(dosso11_1_fish_shp, "-56874.4652709956 227001.00592041", "-56874.4652709956 227011.00592041", "12.5", "12.5", "", "", "-31874.4652709963 252416.056345019", "NO_LABELS", d111, "POLYGON")
#
# # Process: Create Fishnet (12)
# arcpy.CreateFishnet_management(dosso12_1_fish_shp, "-6874.46527099705 227001.00592041", "-6874.46527099705 227011.00592041", "12.5", "12.5", "", "", "18125.5347290029 277001.00592041", "NO_LABELS", d121, "POLYGON")
#
# # Process: Create Fishnet (13)
# arcpy.CreateFishnet_management(dosso14_fish_shp, "93125.5347290028 227001.00592041", "93125.5347290028 227011.00592041", "12.5", "12.5", "", "", "133401.544057246 277001.005920411", "NO_LABELS", d14, "POLYGON")
#
# # Process: Create Fishnet (14)
# arcpy.CreateFishnet_management(dosso15_fish_shp, "-53202.8202130517 196736.317849104", "-53202.8202130517 196746.317849104", "12.5", "12.5", "", "", "-6874.46527099705 227001.00592041", "NO_LABELS", d15, "POLYGON")
#
# # Process: Create Fishnet (15)
# arcpy.CreateFishnet_management(dosso16_1_fish_shp, "-6874.46527099705 185543.525324836", "-6874.46527099705 185553.525324836", "12.5", "12.5", "", "", "18125.5347290022 227001.005920413", "NO_LABELS", d161, "POLYGON")
#
# # Process: Create Fishnet (16)
# arcpy.CreateFishnet_management(dosso17_1_fish_shp, "43125.5347290043 177001.005920412", "43125.5347290043 177011.005920412", "12.5", "12.5", "", "", "68125.5347290043 227001.005920412", "NO_LABELS", d171, "POLYGON")
#
# # Process: Create Fishnet (17)
# arcpy.CreateFishnet_management(dosso18_fish_shp, "43125.5347290043 177001.005920412", "43125.5347290043 177011.005920412", "12.5", "12.5", "", "", "93125.5347290028 227001.00592041", "NO_LABELS", d18, "POLYGON")

# Process: Create Fishnet (18)
#arcpy.CreateFishnet_management(dosso19_fish_shp, "-28299.4080810534 145041.358644446", "-28299.4080810534 145051.358644446", "12.5", "12.5", "", "", "-6874.46527099705 161649.785879906", "NO_LABELS", d19, "POLYGON")

# Process: Create Fishnet
# arcpy.CreateFishnet_management(dosso20_1_fish_shp, "-6874.46519999951 127001.005899999", "-6874.46519999951 127011.005899999", "12.5", "12.5", "", "", "18125.5348000005 148001.150299999", "NO_LABELS", d201, "POLYGON")
#
# # Process: Create Fishnet (2)
# arcpy.CreateFishnet_management(dosso20_2_fish_shp, "18125.5348000005 127001.005899999", "18125.5348000005 127011.005899999", "12.5", "12.5", "", "", "43125.5348000005 177001.005899999", "NO_LABELS", d202, "POLYGON")
#
# # Process: Create Fishnet (20)
# arcpy.CreateFishnet_management(dosso21_fish_shp, "43125.5347290043 127001.00592041", "43125.5347290043 127011.00592041", "12.5", "12.5", "", "", "79922.507646227 177001.005920412", "NO_LABELS", d21, "POLYGON")
#
# # Process: Create Fishnet (21)
# arcpy.CreateFishnet_management(dosso22_fish_shp, "14656.6981072921 97807.63014746", "14656.6981072921 97817.63014746", "12.5", "12.5", "", "", "43125.5347290043 127001.00592041", "NO_LABELS", d22, "POLYGON")
#
# # Process: Create Fishnet (22)
# arcpy.CreateFishnet_management(dosso23_fish_shp, "43125.5347290043 77001.0059204088", "43125.5347290043 77011.0059204088", "12.5", "12.5", "", "", "74611.2262573286 127001.00592041", "NO_LABELS", d23, "POLYGON")

# Process: Create Fishnet (2)
arcpy.CreateFishnet_management(dosso4_2_fish_shp, "118125.534729003 327001.00592041", "118125.534729003 327011.00592041", "12.5", "12.5", "", "", "143125.534729003 377001.00592041", "NO_LABELS", d42, "POLYGON")

# Process: Create Fishnet (3)
arcpy.CreateFishnet_management(dosso8_2_fish_shp, "68125.5347290036 277001.005920411", "68125.5347290036 277011.005920411", "12.5", "12.5", "", "", "93125.5347290028 327001.00592041", "NO_LABELS", d82, "POLYGON")

# Process: Create Fishnet (23)
arcpy.CreateFishnet_management(dosso9_2_fish_shp, "118125.534729002 277001.005920411", "118125.534729002 277011.005920411", "12.5", "12.5", "", "", "143125.534729004 327001.005920413", "NO_LABELS", d92, "POLYGON")

# Process: Create Fishnet
arcpy.CreateFishnet_management(dosso13_1_fish_shp, "43125.5347290039 227001.00592041", "43125.5347290039 227011.00592041", "12.5", "12.5", "", "", "68125.5347290039 277001.00592041", "NO_LABELS", d131, "POLYGON")

# Process: Create Fishnet (24)
arcpy.CreateFishnet_management(dosso13_2_fish_shp, "68125.5347290039 227001.00592041", "68125.5347290039 227011.00592041", "12.5", "12.5", "", "", "93125.5347290039 277001.00592041", "NO_LABELS", d132, "POLYGON")

# Process: Create Fishnet (25)
arcpy.CreateFishnet_management(dosso12_2_fish_shp, "18125.5347290029 227001.00592041", "18125.5347290029 227011.00592041", "12.5", "12.5", "", "", "43125.5347290029 277001.00592041", "NO_LABELS", d122, "POLYGON")

# Process: Create Fishnet (26)
arcpy.CreateFishnet_management(dosso16_2_fish_shp, "18125.5347290022 177001.005920412", "18125.5347290022 177011.005920412", "12.5", "12.5", "", "", "43125.5347290043 227001.005920413", "NO_LABELS", d162, "POLYGON")

# Process: Create Fishnet (27)
arcpy.CreateFishnet_management(dosso17_2_fish_shp, "68125.5347290036 177001.005920412", "68125.5347290036 177011.005920412", "12.5", "12.5", "", "", "93125.5347290057 227001.005920413", "NO_LABELS", d172, "POLYGON")

# Process: Create Fishnet (28)
arcpy.CreateFishnet_management(dosso11_2_fish_shp, "-31874.4652709963 227001.00592041", "-31874.4652709963 227011.00592041", "12.5", "12.5", "", "", "-6874.46527099422 277001.005920411", "NO_LABELS", d112, "POLYGON")

