# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# index_dosso.py
# Created on: 2020-01-22 13:15:44.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
dosso_index_10k_clip_shp = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index\\dosso_index_10k_clip.shp"
index0_shp = dosso_index_10k_clip_shp
dosso_index = "C:\\Users\\Research\\Documents\\Tara_Fall_2019\\dosso_index"

# Process: Feature Class to Feature Class
for i in range(347):
    #base sql input to select feature by FID
    SQL = "\"FID\" ="
    #base name of the file
    outname = "index"
    #string index to add to file name andsql input
    index = str(i)
    #output file name with index
    outname_index = outname + index + ".shp"
    #input sql code with index
    iter = SQL+index
    #run command with index specific variables
    arcpy.FeatureClassToFeatureClass_conversion(dosso_index_10k_clip_shp, dosso_index, outname_index, iter, "", "")
